-- =====================================================================
-- CONFIGURACIÓN DE BASE DE DATOS DE ZONA DE MIEMBROS - CENTRO DE TUTORÍAS
-- =====================================================================
-- Ejecuta este script en el SQL Editor de tu proyecto de Supabase.

-- -----------------------------------------------------
-- 1. Tabla de Perfiles Públicos (Extiende auth.users)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    role TEXT DEFAULT 'free_user' CHECK (role IN ('free_user', 'subscriber', 'admin')),
    subscription_status TEXT DEFAULT 'inactive' CHECK (subscription_status IN ('active', 'inactive', 'trial', 'cancelled', 'expired')),
    academic_level TEXT,
    main_interest TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_login TIMESTAMP WITH TIME ZONE
);

-- Habilitar Seguridad a Nivel de Fila (RLS) en la tabla users
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------------
-- 1.1 Funciones Auxiliares de Seguridad (Evitan recursión infinita en RLS)
-- -----------------------------------------------------
CREATE OR REPLACE FUNCTION public.is_admin(user_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.users
    WHERE id = user_id AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_subscriber(user_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.users
    WHERE id = user_id AND role = 'subscriber'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.has_premium_access(user_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.users
    WHERE id = user_id AND (role = 'subscriber' OR role = 'admin')
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Políticas RLS para users
CREATE POLICY "Permitir a los usuarios ver su propio perfil" 
    ON public.users FOR SELECT 
    USING (auth.uid() = id);

CREATE POLICY "Permitir a los usuarios actualizar su propio perfil" 
    ON public.users FOR UPDATE 
    USING (auth.uid() = id);

CREATE POLICY "Permitir a los administradores ver todos los perfiles" 
    ON public.users FOR SELECT 
    USING (public.is_admin(auth.uid()));

CREATE POLICY "Permitir a los administradores actualizar cualquier perfil" 
    ON public.users FOR UPDATE 
    USING (public.is_admin(auth.uid()));

-- -----------------------------------------------------
-- 2. Tabla de Categorías
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS en categories
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- Políticas RLS para categories
CREATE POLICY "Permitir a cualquiera ver categorías" 
    ON public.categories FOR SELECT 
    USING (true);

CREATE POLICY "Permitir solo a administradores modificar categorías" 
    ON public.categories FOR ALL 
    USING (public.is_admin(auth.uid()));

-- -----------------------------------------------------
-- 3. Tabla de Contenidos (Cursos, Artículos, Ejercicios)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.content_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    academic_level TEXT, -- Primaria, Secundaria, Universidad, etc.
    content_type TEXT NOT NULL CHECK (content_type IN ('video', 'pdf', 'article', 'exercise', 'download', 'course', 'lesson')),
    access_type TEXT NOT NULL DEFAULT 'free' CHECK (access_type IN ('free', 'premium', 'subscriber_only')),
    thumbnail_url TEXT,
    video_url TEXT,
    document_url TEXT,
    body_content TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS en content_items
ALTER TABLE public.content_items ENABLE ROW LEVEL SECURITY;

-- Políticas RLS para content_items
CREATE POLICY "Permitir a usuarios ver contenidos libres o sus propios accesos" 
    ON public.content_items FOR SELECT 
    USING (
        access_type = 'free' 
        OR public.has_premium_access(auth.uid())
    );

CREATE POLICY "Permitir a administradores realizar todo en content_items" 
    ON public.content_items FOR ALL 
    USING (public.is_admin(auth.uid()));

-- -----------------------------------------------------
-- 4. Tabla de Progreso de Usuarios
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_content_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    content_id BIGINT REFERENCES public.content_items(id) ON DELETE CASCADE NOT NULL,
    status TEXT NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started', 'in_progress', 'completed')),
    progress_percentage INTEGER DEFAULT 0 CHECK (progress_percentage >= 0 AND progress_percentage <= 100),
    started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    completed_at TIMESTAMP WITH TIME ZONE,
    last_accessed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(user_id, content_id)
);

-- Habilitar RLS en user_content_progress
ALTER TABLE public.user_content_progress ENABLE ROW LEVEL SECURITY;

-- Políticas RLS para user_content_progress
CREATE POLICY "Permitir a usuarios ver su propio progreso" 
    ON public.user_content_progress FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Permitir a usuarios actualizar su propio progreso" 
    ON public.user_content_progress FOR ALL 
    USING (auth.uid() = user_id);

CREATE POLICY "Permitir a administradores ver todos los progresos" 
    ON public.user_content_progress FOR SELECT 
    USING (public.is_admin(auth.uid()));

-- -----------------------------------------------------
-- 5. Tabla de Suscripciones
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    plan_name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'inactive', 'trial', 'cancelled', 'expired')),
    start_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE,
    payment_provider TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS en subscriptions
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

-- Políticas RLS para subscriptions
CREATE POLICY "Permitir a usuarios ver sus propias suscripciones" 
    ON public.subscriptions FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Permitir a administradores control total sobre suscripciones" 
    ON public.subscriptions FOR ALL 
    USING (public.is_admin(auth.uid()));

-- -----------------------------------------------------
-- 6. Tabla de Solicitudes de Tutorías
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tutoring_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    student_name TEXT NOT NULL,
    academic_level TEXT NOT NULL,
    subject TEXT NOT NULL,
    problem_description TEXT NOT NULL,
    preferred_schedule TEXT,
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'scheduled', 'completed', 'cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS en tutoring_requests
ALTER TABLE public.tutoring_requests ENABLE ROW LEVEL SECURITY;

-- Políticas RLS para tutoring_requests
CREATE POLICY "Permitir a usuarios ver sus propias solicitudes de tutorías" 
    ON public.tutoring_requests FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Permitir a usuarios crear sus propias solicitudes" 
    ON public.tutoring_requests FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Permitir a administradores ver todas las solicitudes" 
    ON public.tutoring_requests FOR ALL 
    USING (public.is_admin(auth.uid()));

-- =====================================================================
-- TRIGGERS DE AUTOMATIZACIÓN EN POSTGRESQL
-- =====================================================================

-- 7. Trigger para sincronizar auth.users con public.users automáticamente
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, full_name, email, phone, role, subscription_status, academic_level, main_interest)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', 'Estudiante Nuevo'),
    NEW.email,
    NEW.raw_user_meta_data->>'phone',
    COALESCE(NEW.raw_user_meta_data->>'role', 'free_user'),
    'inactive',
    NEW.raw_user_meta_data->>'academic_level',
    NEW.raw_user_meta_data->>'main_interest'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 8. Trigger para actualizar el estado del perfil de usuario tras suscribirse
CREATE OR REPLACE FUNCTION public.handle_subscription_change()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.users 
  SET subscription_status = NEW.status,
      role = CASE WHEN NEW.status = 'active' THEN 'subscriber' ELSE 'free_user' END
  WHERE id = NEW.user_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_subscription_change ON public.subscriptions;
CREATE TRIGGER on_subscription_change
  AFTER INSERT OR UPDATE ON public.subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.handle_subscription_change();


-- =====================================================================
-- DATOS SEMILLA (SEED DATA)
-- =====================================================================

-- 9. Insertar Categorías Iniciales
INSERT INTO public.categories (name, slug, description) VALUES
('Matemática', 'matematica', 'Refuerzo en álgebra, cálculo, geometría y aritmética para todos los niveles.'),
('Física', 'fisica', 'Dinámica, cinemática, electromagnetismo y leyes del movimiento.'),
('Estadística', 'estadistica', 'Estadística descriptiva, probabilidad, inferencial y modelado de datos.'),
('Hábitos de estudio', 'habitos-estudio', 'Técnicas de estudio, gestión del tiempo escolar y metodologías efectivas.'),
('Preparación para exámenes', 'preparacion-examenes', 'Estrategias y checklists antes de evaluaciones complejas y exámenes de admisión.'),
('Universidad', 'universidad', 'Temas avanzados de cálculo, álgebra lineal y física para universitarios.'),
('Secundaria', 'secundaria', 'Temas escolares de nivel medio, secundaria y bachillerato.'),
('Diversificado', 'diversificado', 'Materias para estudiantes de nivel diversificado (bachillerato, perito, secretariado).'),
('Recursos para padres', 'recursos-padres', 'Guías útiles para que los padres puedan apoyar el aprendizaje en el hogar.')
ON CONFLICT (slug) DO NOTHING;

-- 10. Insertar Contenidos de Ejemplo (Guías, cursos, etc.)
-- Nota: Usamos subconsultas para asociar los category_id correspondientes basados en el slug.

-- Contenidos Gratuitos:
INSERT INTO public.content_items (title, slug, description, category_id, academic_level, content_type, access_type, thumbnail_url, video_url, document_url, body_content, status) VALUES
('Guía para organizar mejor el tiempo de estudio', 
 'guia-organizar-tiempo', 
 'Aprende una metodología sencilla para organizar tu tiempo y prepararte mejor antes de una evaluación.',
 (SELECT id FROM public.categories WHERE slug = 'habitos-estudio'),
 'Secundaria', 'article', 'free',
 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?q=80&w=300&auto=format&fit=crop',
 NULL, NULL, 
 '# Guía Práctica de Gestión del Tiempo de Estudio\n\nEstudiar a última hora genera estrés y resultados deficientes. Utiliza este método de 3 pasos:\n\n### 1. El Método del Bloque de Enfoque (Pomodoro)\nTrabaja en bloques de 25 minutos de estudio ininterrumpido seguidos de 5 minutos de descanso. Realiza 4 bloques y luego toma un descanso largo de 20 minutos.\n\n### 2. Priorización de Tareas (Matriz Eisenhower)\nDivide tus deberes en:\n* **Urgente e Importante**: Repasar los temas del examen de mañana.\n* **No Urgente pero Importante**: Leer la lección del próximo lunes.\n\n### 3. Planifica tu semana\nDedica 10 minutos los domingos a agendar tus sesiones de estudio y compromisos principales.',
 'active'),

('Diagnóstico inicial de hábitos de estudio', 
 'diagnostico-habitos-estudio', 
 'Evalúa tus conocimientos básicos para identificar áreas de mejora.',
 (SELECT id FROM public.categories WHERE slug = 'habitos-estudio'),
 'Secundaria', 'exercise', 'free',
 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=300&auto=format&fit=crop',
 NULL, NULL,
 '# Test de Autodiagnóstico de Hábitos de Estudio\n\nResponde honestamente a estas 5 preguntas para evaluar tu metodología:\n\n1. **¿Estudias en un lugar libre de distracciones (sin celular al lado)?** (Sí / No)\n2. **¿Planificas tus sesiones de estudio con al menos 3 días de anticipación?** (Sí / No)\n3. **¿Utilizas técnicas activas de aprendizaje (ejercicios, resúmenes) en lugar de solo leer?** (Sí / No)\n4. **¿Duermes al menos 7 u 8 horas la noche anterior a un examen?** (Sí / No)\n5. **¿Haces pausas regulares durante sesiones de estudio largas?** (Sí / No)\n\n*Resultado:* Si respondiste "No" a más de 2 preguntas, necesitas optimizar tus hábitos académicos. ¡Pide ayuda a tu tutor! ',
 'active'),

('Introducción a técnicas de aprendizaje efectivo', 
 'tecnicas-aprendizaje-efectivo', 
 'Aprende cómo procesar información más rápido utilizando técnicas científicas como la repetición espaciada y el recuerdo activo.',
 (SELECT id FROM public.categories WHERE slug = 'habitos-estudio'),
 'Universidad', 'article', 'free',
 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=300&auto=format&fit=crop',
 NULL, NULL,
 '# Técnicas Científicas de Aprendizaje Rápido\n\nEl cerebro aprende mejor a través del esfuerzo cognitivo. Olvídate de releer pasivamente. Usa estas dos técnicas comprobadas por neurociencia:\n\n### 1. Active Recall (Recuerdo Activo)\nAl terminar de leer una página de estudio, cierra el libro e intenta escribir en una hoja en blanco o explicar en voz alta todo lo que recuerdas. Esto refuerza las conexiones sinápticas de forma inmediata.\n\n### 2. Spaced Repetition (Repetición Espaciada)\nEn lugar de estudiar 5 horas seguidas un día, repasa el tema en intervalos crecientes: el día 1, el día 3, el día 7 y el día 14. Así evitarás la curva del olvido y retendrás el conocimiento permanentemente.',
 'active'),

('Checklist para prepararse antes de un examen', 
 'checklist-antes-examen', 
 'Descarga este checklist en PDF para asegurarte de que tienes todo listo antes de tu gran prueba académica.',
 (SELECT id FROM public.categories WHERE slug = 'preparacion-examenes'),
 'Secundaria', 'download', 'free',
 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?q=80&w=300&auto=format&fit=crop',
 NULL, 'https://www.centrodetutorias.com/downloads/checklist_examenes_cedetu.pdf',
 'Descarga nuestra plantilla estructurada en formato PDF para organizar tu material, revisar los temas principales y verificar que cuentas con las herramientas permitidas (calculadoras, formularios) antes de entrar a tu evaluación.',
 'active'),

('Errores comunes al estudiar matemática', 
 'errores-comunes-matematica', 
 'Conoce los errores más recurrentes al resolver ecuaciones y cómo evitarlos en tus exámenes escolares o universitarios.',
 (SELECT id FROM public.categories WHERE slug = 'matematica'),
 'Diversificado', 'article', 'free',
 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=300&auto=format&fit=crop',
 NULL, NULL,
 '# Errores Matemáticos Fatales y Cómo Evitarlos\n\nIncluso los mejores estudiantes cometen fallos mecánicos sencillos que les restan puntos valiosos en sus pruebas de matemática. Analicemos los 3 errores más comunes:\n\n### 1. El signo negativo fuera del paréntesis\nUn signo negativo fuera de un paréntesis cambia el signo de **todos** los términos internos. \n* *Incorrecto:* `-(x - 3) = -x - 3` \n* *Correcto:* `-(x - 3) = -x + 3`\n\n### 2. Mal uso de la simplificación de fracciones algebraicas\nSolo puedes simplificar términos que se están multiplicando, ¡nunca los que se están sumando!\n* *Incorrecto:* En `(x + 2) / x`, no puedes eliminar la `x` para que quede `2`.\n* *Correcto:* Simplificar `x(y + 2) / x` para que quede `y + 2`.\n\n### 3. Elevar un binomio al cuadrado de forma incorrecta\nEl cuadrado de un binomio siempre resulta en un trinomio. No te olvides del término del medio.\n* *Incorrecto:* `(a + b)² = a² + b²` \n* *Correcto:* `(a + b)² = a² + 2ab + b²`',
 'active')
ON CONFLICT (slug) DO NOTHING;

-- Contenidos Premium / Exclusivos para Suscriptores:
INSERT INTO public.content_items (title, slug, description, category_id, academic_level, content_type, access_type, thumbnail_url, video_url, document_url, body_content, status) VALUES
('Curso de refuerzo en matemática básica', 
 'curso-matematica-basica', 
 'Curso práctico para fortalecer operaciones algebraicas, ecuaciones y resolución de problemas cotidianos.',
 (SELECT id FROM public.categories WHERE slug = 'matematica'),
 'Secundaria', 'course', 'premium',
 'https://images.unsplash.com/photo-1596495578065-6e076b8ae1d8?q=80&w=300&auto=format&fit=crop',
 'https://www.youtube.com/embed/dQw4w9WgXcQ', NULL,
 '## Temario Completo del Curso de Matemática Básica\n\nEste curso premium está estructurado para llevarte paso a paso desde las bases del álgebra hasta las ecuaciones.\n\n### Módulo 1: Operaciones fundamentales con números enteros y fracciones.\n### Módulo 2: Introducción al lenguaje algebraico y términos semejantes.\n### Módulo 3: Ecuaciones lineales de una y dos variables.\n### Módulo 4: Aplicaciones prácticas e interpretación de problemas verbales.\n\n*Incluye ejercicios interactivos y evaluaciones cortas al final de cada unidad.*',
 'active'),

('Curso de álgebra para secundaria', 
 'curso-algebra-secundaria', 
 'Aprende de forma intuitiva polinomios, factorización y sistemas de ecuaciones lineales paso a paso.',
 (SELECT id FROM public.categories WHERE slug = 'matematica'),
 'Secundaria', 'course', 'premium',
 'https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=300&auto=format&fit=crop',
 'https://www.youtube.com/embed/dQw4w9WgXcQ', NULL,
 '## Conquista el Álgebra Escolar\n\nEl álgebra es la llave del éxito escolar. Con este temario interactivo dejarás de ver letras en lugar de números y entenderás la lógica del álgebra:\n\n* **Semana 1:** Leyes de exponentes y radicales.\n* **Semana 2:** Multiplicación de polinomios y productos notables.\n* **Semana 3:** Técnicas clave de factorización (diferencia de cuadrados, trinomios).\n* **Semana 4:** Sistemas de ecuaciones 2x2 resueltos por métodos analíticos y gráficos.',
 'active'),

('Curso de física introductoria', 
 'curso-fisica-introductoria', 
 'Aprende los conceptos esenciales de movimiento, fuerza, energía y resolución de ejercicios de física.',
 (SELECT id FROM public.categories WHERE slug = 'fisica'),
 'Secundaria', 'course', 'premium',
 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=300&auto=format&fit=crop',
 'https://www.youtube.com/embed/dQw4w9WgXcQ', NULL,
 '## Física Descomplicada para Bachillerato\n\nEntiende el comportamiento del universo físico de forma visual y con ejemplos cotidianos. Deja de memorizar fórmulas vacías:\n\n* **Unidad 1:** Cinemática de una dimensión (MRU y MRUA).\n* **Unidad 2:** Dinámica vectorial y Leyes de Newton.\n* **Unidad 3:** Concepto de Trabajo, Potencia y Conservación de la Energía Mecánica.\n* **Unidad 4:** Ejercicios de aplicación y examen de simulación resuelto en video.',
 'active'),

('Curso de estadística aplicada', 
 'curso-estadistica-aplicada', 
 'Estadística descriptiva e inferencial explicada paso a paso para estudiantes universitarios y de bachillerato.',
 (SELECT id FROM public.categories WHERE slug = 'estadistica'),
 'Universidad', 'course', 'premium',
 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=300&auto=format&fit=crop',
 'https://www.youtube.com/embed/dQw4w9WgXcQ', NULL,
 '## Domina el Análisis de Datos y la Probabilidad\n\nEspecialmente diseñado para superar las materias universitarias de estadística aplicadas a ciencias, ingeniería y negocios:\n\n* **Módulo 1:** Medidas de tendencia central y dispersión (Varianza, Desviación Estándar).\n* **Módulo 2:** Teoría de probabilidad básica y distribuciones discretas (Binomial, Poisson).\n* **Módulo 3:** Distribución Normal y el Teorema del Límite Central.\n* **Módulo 4:** Pruebas de hipótesis e intervalos de confianza para toma de decisiones.',
 'active'),

('Preparación para exámenes de admisión', 
 'preparacion-admision-universidad', 
 'Domina el temario oficial de las principales pruebas de admisión universitaria en matemáticas y física.',
 (SELECT id FROM public.categories WHERE slug = 'preparacion-examenes'),
 'Universidad', 'course', 'premium',
 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=300&auto=format&fit=crop',
 'https://www.youtube.com/embed/dQw4w9WgXcQ', NULL,
 '## Asegura tu ingreso a la Universidad\n\nEste curso prepara el razonamiento matemático y de física requerido para las principales pruebas de ingreso de universidades nacionales e internacionales:\n\n* **Aritmética y Razonamiento Lógico:** Razones, proporciones y series.\n* **Álgebra Avanzada:** Ecuaciones de segundo grado y logaritmos.\n* **Geometría y Trigonometría:** Ángulos, triángulos rectángulos, Teorema de Pitágoras e identidades trigonométricas.\n* **Simulador de examen:** 3 pruebas completas cronometradas con retroalimentación en video.',
 'active'),

('Biblioteca de ejercicios resueltos', 
 'biblioteca-ejercicios-resueltos', 
 'Accede a más de 500 problemas de exámenes pasados resueltos por profesores en video y formato PDF imprimible.',
 (SELECT id FROM public.categories WHERE slug = 'matematica'),
 'Diversificado', 'download', 'premium',
 'https://images.unsplash.com/photo-1517842645767-c639042777db?q=80&w=300&auto=format&fit=crop',
 NULL, 'https://www.centrodetutorias.com/downloads/ejercicios_resueltos_algebra.pdf',
 'Nuestra biblioteca de ejercicios resueltos es el recurso definitivo para repasar de forma autónoma. Contiene problemas reales de exámenes ordenados por dificultad (básico, intermedio y avanzado) con soluciones detalladas paso a paso en PDF y explicaciones breves en video para evitar bloqueos mentales durante el repaso.',
 'active'),

('Sesiones grabadas de refuerzo académico', 
 'sesiones-grabadas-refuerzo', 
 'Revive las clases y tutorías grupales grabadas por nuestros mejores profesores de CEDETU.',
 (SELECT id FROM public.categories WHERE slug = 'universidad'),
 'Universidad', 'video', 'premium',
 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=300&auto=format&fit=crop',
 'https://www.youtube.com/embed/dQw4w9WgXcQ', NULL,
 '## Revive y Repasa las Sesiones en Vivo\n\nSi te perdiste alguna de nuestras clases de repaso grupal antes de los exámenes parciales, aquí tienes acceso ilimitado a las grabaciones en alta definición. Incluye pizarras digitales y preguntas y respuestas reales de otros estudiantes para consolidar tu conocimiento.',
 'active'),

('Guías descargables premium', 
 'guias-descargables-premium', 
 'Accede a plantillas, formularios y resúmenes estructurados listos para imprimir y repasar antes de clase.',
 (SELECT id FROM public.categories WHERE slug = 'secundaria'),
 'Secundaria', 'download', 'premium',
 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?q=80&w=300&auto=format&fit=crop',
 NULL, 'https://www.centrodetutorias.com/downloads/guias_estudio_premium.pdf',
 'Formularios interactivos descargables de geometría, trigonometría, álgebra de polinomios y física clásica. Ideal para pegar en tu cuaderno o escritorio y repasar antes de realizar tus exámenes prácticos.',
 'active')
ON CONFLICT (slug) DO NOTHING;
