-- =====================================================================
-- CONFIGURACIÓN DE TABLA DE RENDIMIENTO DE CONTENIDO EN REDES SOCIALES
-- =====================================================================
-- Ejecuta este script en tu gestor de base de datos o editor de Supabase.
-- Esta tabla permite almacenar el historial de métricas para análisis de 
-- series de tiempo, detección de tendencias y optimización de contenido.

CREATE TABLE IF NOT EXISTS public.social_media_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id VARCHAR(100) NOT NULL,
    platform VARCHAR(50) NOT NULL DEFAULT 'meta' CHECK (platform IN ('meta', 'facebook', 'instagram', 'tiktok', 'youtube', 'other')),
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    format VARCHAR(50) NOT NULL CHECK (format IN ('Reel', 'Carrusel', 'Imagen', 'Video', 'Historia', 'Otro')),
    message_type VARCHAR(100) NOT NULL,
    content_intent VARCHAR(50) NOT NULL CHECK (content_intent IN ('Atracción', 'Educación', 'Conversión', 'Desconocido')),
    post_text TEXT,
    permalink TEXT,
    reach INTEGER NOT NULL DEFAULT 0,
    views INTEGER NOT NULL DEFAULT 0,
    reactions INTEGER NOT NULL DEFAULT 0,
    comments INTEGER NOT NULL DEFAULT 0,
    shares INTEGER NOT NULL DEFAULT 0,
    total_clicks INTEGER NOT NULL DEFAULT 0,
    link_clicks INTEGER NOT NULL DEFAULT 0,
    engagement_rate NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
    ctr NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
    video_duration_seconds INTEGER DEFAULT 0,
    avg_watch_time_seconds NUMERIC(6, 2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Clave única para evitar duplicados al re-importar la misma publicación
    CONSTRAINT unique_publication_platform UNIQUE (publication_id, platform)
);

-- Índices de optimización para series de tiempo y agrupaciones
CREATE INDEX IF NOT EXISTS idx_social_perf_date ON public.social_media_performance (published_at DESC);
CREATE INDEX IF NOT EXISTS idx_social_perf_platform_format ON public.social_media_performance (platform, format);
CREATE INDEX IF NOT EXISTS idx_social_perf_msg_intent ON public.social_media_performance (message_type, content_intent);

-- Comentario descriptivo de la tabla
COMMENT ON TABLE public.social_media_performance IS 'Registro histórico de rendimiento de publicaciones orgánicas y pautadas en canales sociales.';

-- =====================================================================
-- DATOS HISTÓRICOS SEMILLA (REPORTE DE META - JUNIO 2026)
-- =====================================================================
INSERT INTO public.social_media_performance (
    publication_id, platform, published_at, format, message_type, content_intent, 
    post_text, permalink, reach, views, reactions, comments, shares, 
    total_clicks, link_clicks, engagement_rate, ctr, video_duration_seconds, avg_watch_time_seconds
) VALUES (
    '1308501324810305', 
    'meta', 
    '06/18/2026 21:32', 
    'Carrusel', 
    'Educación', 
    'Atracción', 
    'Cada estudiante aprende distinto y merece una explicación diferente
Repetir la misma explicación más veces no siempre funciona. A veces hay que cambiar el ejemplo, el ritmo o el punto de partida.
En Centro de Tutorías, personalizamos la sesión y verificamos comprensión durante el proceso, no solamente al final del ejercicio.
Conoce nuestras tutorías: https://www.centrodetutorias.com\nWhatsApp: +502 5715 2096', 
    'https://www.facebook.com/centrodetutoriasgt/posts/pfbid0iMcNrBUrcvaHswoc1b59aeUg6waaYSLWgzd8sAdBCpD3FV6dssGqdDonf8m9TJgcl', 
    35, 
    65, 
    1, 
    0, 
    2, 
    3, 
    1, 
    8.57, 
    8.57, 
    0, 
    0.0
) ON CONFLICT (publication_id, platform) DO UPDATE SET
    reach = EXCLUDED.reach,
    views = EXCLUDED.views,
    reactions = EXCLUDED.reactions,
    comments = EXCLUDED.comments,
    shares = EXCLUDED.shares,
    total_clicks = EXCLUDED.total_clicks,
    link_clicks = EXCLUDED.link_clicks,
    engagement_rate = EXCLUDED.engagement_rate,
    ctr = EXCLUDED.ctr,
    avg_watch_time_seconds = EXCLUDED.avg_watch_time_seconds,
    updated_at = timezone('utc'::text, now());

INSERT INTO public.social_media_performance (
    publication_id, platform, published_at, format, message_type, content_intent, 
    post_text, permalink, reach, views, reactions, comments, shares, 
    total_clicks, link_clicks, engagement_rate, ctr, video_duration_seconds, avg_watch_time_seconds
) VALUES (
    '1316392790687825', 
    'meta', 
    '06/28/2026 07:29', 
    'Reel', 
    'Dolor', 
    'Atracción', 
    'Cuando las tareas se acumulan, la frustración en casa crece

La acumulación suele esconder un vacío conceptual: un paso algebraico o un signo que no quedó claro en la clase presencial.

En Centro de Tutorías, dividimos los problemas grandes en pasos sencillos y guiamos al estudiante hasta que recupere la autonomía para resolver solo.

Agenda tutoría de apoyo: https://www.centrodetutorias.com
Chatea con nosotros por WhatsApp: https://wa.me/50257152096', 
    'https://www.facebook.com/reel/883298300883175/', 
    42, 
    44, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0.0, 
    0.0, 
    52, 
    3.06
) ON CONFLICT (publication_id, platform) DO UPDATE SET
    reach = EXCLUDED.reach,
    views = EXCLUDED.views,
    reactions = EXCLUDED.reactions,
    comments = EXCLUDED.comments,
    shares = EXCLUDED.shares,
    total_clicks = EXCLUDED.total_clicks,
    link_clicks = EXCLUDED.link_clicks,
    engagement_rate = EXCLUDED.engagement_rate,
    ctr = EXCLUDED.ctr,
    avg_watch_time_seconds = EXCLUDED.avg_watch_time_seconds,
    updated_at = timezone('utc'::text, now());

INSERT INTO public.social_media_performance (
    publication_id, platform, published_at, format, message_type, content_intent, 
    post_text, permalink, reach, views, reactions, comments, shares, 
    total_clicks, link_clicks, engagement_rate, ctr, video_duration_seconds, avg_watch_time_seconds
) VALUES (
    '1314667664193671', 
    'meta', 
    '06/26/2026 06:20', 
    'Reel', 
    'Confianza', 
    'Educación', 
    'Si te dice ''no puedo con mate'', necesita otra forma de explicación

Cuando alguien anticipa que fallará, deja de intentar. La dificultad en matemáticas golpea la autoestima del estudiante rápidamente.

En Centro de Tutorías, trabajamos con metas pequeñas y retroalimentación positiva e inmediata para que experimente el éxito desde la primera sesión.

Recupera su confianza: https://www.centrodetutorias.com
Chatea con nosotros por WhatsApp: https://wa.me/50257152096', 
    'https://www.facebook.com/reel/1351694689845512/', 
    220, 
    232, 
    1, 
    0, 
    0, 
    3, 
    0, 
    0.45, 
    1.36, 
    65, 
    3.07
) ON CONFLICT (publication_id, platform) DO UPDATE SET
    reach = EXCLUDED.reach,
    views = EXCLUDED.views,
    reactions = EXCLUDED.reactions,
    comments = EXCLUDED.comments,
    shares = EXCLUDED.shares,
    total_clicks = EXCLUDED.total_clicks,
    link_clicks = EXCLUDED.link_clicks,
    engagement_rate = EXCLUDED.engagement_rate,
    ctr = EXCLUDED.ctr,
    avg_watch_time_seconds = EXCLUDED.avg_watch_time_seconds,
    updated_at = timezone('utc'::text, now());

INSERT INTO public.social_media_performance (
    publication_id, platform, published_at, format, message_type, content_intent, 
    post_text, permalink, reach, views, reactions, comments, shares, 
    total_clicks, link_clicks, engagement_rate, ctr, video_duration_seconds, avg_watch_time_seconds
) VALUES (
    '1313996817594089', 
    'meta', 
    '06/25/2026 10:30', 
    'Carrusel', 
    'Diagnóstico', 
    'Conversión', 
    'Estudiar más horas no sirve si no sabes dónde está el vacío

Repasar todo el libro no es eficiente. Enfocar el esfuerzo en la debilidad raíz (ej. fracciones, despejes) ahorra semanas de estudio frustrante.

En Centro de Tutorías, evaluamos brevemente las destrezas de resolución y te entregamos un mapa detallado del nivel de tu hijo y qué necesita reforzar.

Solicita diagnóstico gratis: https://www.centrodetutorias.com
Chatea con nosotros por WhatsApp: https://wa.me/50257152096', 
    'https://www.facebook.com/centrodetutoriasgt/posts/pfbid02aaF8FLGAEcWZKHc7JLTcL7LeFyiV3KwH23VEeGLCFL1NhvtxhcNDnZZzCjETKf5hl', 
    1, 
    2, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0.0, 
    0.0, 
    0, 
    0.0
) ON CONFLICT (publication_id, platform) DO UPDATE SET
    reach = EXCLUDED.reach,
    views = EXCLUDED.views,
    reactions = EXCLUDED.reactions,
    comments = EXCLUDED.comments,
    shares = EXCLUDED.shares,
    total_clicks = EXCLUDED.total_clicks,
    link_clicks = EXCLUDED.link_clicks,
    engagement_rate = EXCLUDED.engagement_rate,
    ctr = EXCLUDED.ctr,
    avg_watch_time_seconds = EXCLUDED.avg_watch_time_seconds,
    updated_at = timezone('utc'::text, now());

INSERT INTO public.social_media_performance (
    publication_id, platform, published_at, format, message_type, content_intent, 
    post_text, permalink, reach, views, reactions, comments, shares, 
    total_clicks, link_clicks, engagement_rate, ctr, video_duration_seconds, avg_watch_time_seconds
) VALUES (
    '1313992947594476', 
    'meta', 
    '06/25/2026 10:24', 
    'Carrusel', 
    'Diagnóstico', 
    'Conversión', 
    'Estudiar más horas no sirve si no sabes dónde está el vacío

Repasar todo el libro no es eficiente. Enfocar el esfuerzo en la debilidad raíz (ej. fracciones, despejes) ahorra semanas de estudio frustrante.

En Centro de Tutorías, evaluamos brevemente las destrezas de resolución y te entregamos un mapa detallado del nivel de tu hijo y qué necesita reforzar.

Solicita diagnóstico gratis: https://www.centrodetutorias.com
Chatea con nosotros por WhatsApp: https://wa.me/50257152096', 
    'https://www.facebook.com/centrodetutoriasgt/posts/pfbid0LpuHrsqme6t5yf4v4QuYJ7KAeTT1c94JbUjDLpGvEKwefiiUnV25AsMRCoeR3yCml', 
    2, 
    3, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0.0, 
    0.0, 
    0, 
    0.0
) ON CONFLICT (publication_id, platform) DO UPDATE SET
    reach = EXCLUDED.reach,
    views = EXCLUDED.views,
    reactions = EXCLUDED.reactions,
    comments = EXCLUDED.comments,
    shares = EXCLUDED.shares,
    total_clicks = EXCLUDED.total_clicks,
    link_clicks = EXCLUDED.link_clicks,
    engagement_rate = EXCLUDED.engagement_rate,
    ctr = EXCLUDED.ctr,
    avg_watch_time_seconds = EXCLUDED.avg_watch_time_seconds,
    updated_at = timezone('utc'::text, now());

INSERT INTO public.social_media_performance (
    publication_id, platform, published_at, format, message_type, content_intent, 
    post_text, permalink, reach, views, reactions, comments, shares, 
    total_clicks, link_clicks, engagement_rate, ctr, video_duration_seconds, avg_watch_time_seconds
) VALUES (
    '1313986687595102', 
    'meta', 
    '06/25/2026 10:14', 
    'Reel', 
    'Confianza', 
    'Educación', 
    'Recuperar la confianza también es parte de aprender matemática

Cuando un estudiante anticipa que fallará, participa menos y practica con inseguridad. Esa experiencia también necesita atención.

En Centro de Tutorías, trabajamos con metas pequeñas, retroalimentación clara y práctica guiada para recuperar autonomía académica.

Acompáñalo paso a paso: https://www.centrodetutorias.com
Chatea con nosotros por WhatsApp: https://wa.me/50257152096', 
    'https://www.facebook.com/reel/1745303726491396/', 
    157, 
    160, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0.0, 
    0.0, 
    63, 
    1.46
) ON CONFLICT (publication_id, platform) DO UPDATE SET
    reach = EXCLUDED.reach,
    views = EXCLUDED.views,
    reactions = EXCLUDED.reactions,
    comments = EXCLUDED.comments,
    shares = EXCLUDED.shares,
    total_clicks = EXCLUDED.total_clicks,
    link_clicks = EXCLUDED.link_clicks,
    engagement_rate = EXCLUDED.engagement_rate,
    ctr = EXCLUDED.ctr,
    avg_watch_time_seconds = EXCLUDED.avg_watch_time_seconds,
    updated_at = timezone('utc'::text, now());

INSERT INTO public.social_media_performance (
    publication_id, platform, published_at, format, message_type, content_intent, 
    post_text, permalink, reach, views, reactions, comments, shares, 
    total_clicks, link_clicks, engagement_rate, ctr, video_duration_seconds, avg_watch_time_seconds
) VALUES (
    '1312233277770443', 
    'meta', 
    '06/23/2026 07:42', 
    'Reel', 
    'Confianza', 
    'Educación', 
    'Cuando dice no puedo, quizá necesita otra forma de explicación

Las etiquetas aparecen rápido: “no soy bueno”, “esto no es para mí”. Pero una dificultad específica no define todo su potencial.

En Centro de Tutorías, creamos un espacio seguro para preguntar, reconstruir bases y experimentar avances que cambien su relación con el curso.

Encuentra el apoyo correcto: https://www.centrodetutorias.com
Chatea con nosotros por WhatsApp: https://wa.me/50257152096', 
    'https://www.facebook.com/reel/1453210360163472/', 
    15, 
    21, 
    0, 
    0, 
    0, 
    1, 
    0, 
    0.0, 
    6.67, 
    63, 
    10.14
) ON CONFLICT (publication_id, platform) DO UPDATE SET
    reach = EXCLUDED.reach,
    views = EXCLUDED.views,
    reactions = EXCLUDED.reactions,
    comments = EXCLUDED.comments,
    shares = EXCLUDED.shares,
    total_clicks = EXCLUDED.total_clicks,
    link_clicks = EXCLUDED.link_clicks,
    engagement_rate = EXCLUDED.engagement_rate,
    ctr = EXCLUDED.ctr,
    avg_watch_time_seconds = EXCLUDED.avg_watch_time_seconds,
    updated_at = timezone('utc'::text, now());

INSERT INTO public.social_media_performance (
    publication_id, platform, published_at, format, message_type, content_intent, 
    post_text, permalink, reach, views, reactions, comments, shares, 
    total_clicks, link_clicks, engagement_rate, ctr, video_duration_seconds, avg_watch_time_seconds
) VALUES (
    '1310731574587280', 
    'meta', 
    '06/21/2026 12:12', 
    'Carrusel', 
    'Educación', 
    'Atracción', 
    'Cada estudiante aprende distinto y merece una explicación diferente

Repetir la misma explicación más veces no siempre funciona. A veces hay que cambiar el ejemplo, el ritmo o el punto de partida.

En Centro de Tutorías, personalizamos la sesión y verificamos comprensión durante el proceso, no solamente al final del ejercicio.

Conoce nuestras tutorías: https://www.centrodetutorias.com
Chatea con nosotros por WhatsApp: https://wa.me/50257152096', 
    'https://www.facebook.com/centrodetutoriasgt/posts/pfbid02TGQ89YVjPngerK5vYKdow9eXXHgiQmJGPVyiyfS9Qs9XNbHvwQadTK6WqvC7RpRul', 
    3, 
    6, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0.0, 
    0.0, 
    0, 
    0.0
) ON CONFLICT (publication_id, platform) DO UPDATE SET
    reach = EXCLUDED.reach,
    views = EXCLUDED.views,
    reactions = EXCLUDED.reactions,
    comments = EXCLUDED.comments,
    shares = EXCLUDED.shares,
    total_clicks = EXCLUDED.total_clicks,
    link_clicks = EXCLUDED.link_clicks,
    engagement_rate = EXCLUDED.engagement_rate,
    ctr = EXCLUDED.ctr,
    avg_watch_time_seconds = EXCLUDED.avg_watch_time_seconds,
    updated_at = timezone('utc'::text, now());

INSERT INTO public.social_media_performance (
    publication_id, platform, published_at, format, message_type, content_intent, 
    post_text, permalink, reach, views, reactions, comments, shares, 
    total_clicks, link_clicks, engagement_rate, ctr, video_duration_seconds, avg_watch_time_seconds
) VALUES (
    '1310093034651134', 
    'meta', 
    '06/20/2026 19:50', 
    'Video', 
    'Desconocido', 
    'Desconocido', 
    '', 
    'https://www.facebook.com/centrodetutoriasgt/posts/pfbid0aDw2WrnEzPRTp5x5sRZgQuua9AXKhstmHfQLXhgi4FziLB5a4eSkBbWvao5zRnBvl', 
    3, 
    9, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0.0, 
    0.0, 
    0, 
    0.0
) ON CONFLICT (publication_id, platform) DO UPDATE SET
    reach = EXCLUDED.reach,
    views = EXCLUDED.views,
    reactions = EXCLUDED.reactions,
    comments = EXCLUDED.comments,
    shares = EXCLUDED.shares,
    total_clicks = EXCLUDED.total_clicks,
    link_clicks = EXCLUDED.link_clicks,
    engagement_rate = EXCLUDED.engagement_rate,
    ctr = EXCLUDED.ctr,
    avg_watch_time_seconds = EXCLUDED.avg_watch_time_seconds,
    updated_at = timezone('utc'::text, now());

INSERT INTO public.social_media_performance (
    publication_id, platform, published_at, format, message_type, content_intent, 
    post_text, permalink, reach, views, reactions, comments, shares, 
    total_clicks, link_clicks, engagement_rate, ctr, video_duration_seconds, avg_watch_time_seconds
) VALUES (
    '1310081584652279', 
    'meta', 
    '06/20/2026 19:31', 
    'Reel', 
    'Transición', 
    'Atracción', 
    'La universidad cambia el ritmo, pero no tiene que enfrentarlo solo

En la universidad se asumen conocimientos previos y el curso avanza rápido. Una base débil puede sentirse como falta de capacidad.

En Centro de Tutorías, revisamos fundamentos, lenguaje matemático y formas de estudio para construir una transición académica más sólida.

Solicita apoyo universitario: https://www.centrodetutorias.com
Chatea con nosotros por WhatsApp: https://wa.me/50257152096', 
    'https://www.facebook.com/reel/1723056772229151/', 
    223, 
    238, 
    1, 
    0, 
    2, 
    0, 
    0, 
    1.35, 
    0.0, 
    65, 
    2.07
) ON CONFLICT (publication_id, platform) DO UPDATE SET
    reach = EXCLUDED.reach,
    views = EXCLUDED.views,
    reactions = EXCLUDED.reactions,
    comments = EXCLUDED.comments,
    shares = EXCLUDED.shares,
    total_clicks = EXCLUDED.total_clicks,
    link_clicks = EXCLUDED.link_clicks,
    engagement_rate = EXCLUDED.engagement_rate,
    ctr = EXCLUDED.ctr,
    avg_watch_time_seconds = EXCLUDED.avg_watch_time_seconds,
    updated_at = timezone('utc'::text, now());

INSERT INTO public.social_media_performance (
    publication_id, platform, published_at, format, message_type, content_intent, 
    post_text, permalink, reach, views, reactions, comments, shares, 
    total_clicks, link_clicks, engagement_rate, ctr, video_duration_seconds, avg_watch_time_seconds
) VALUES (
    '1310047281322376', 
    'meta', 
    '06/20/2026 18:33', 
    'Carrusel', 
    'Confianza', 
    'Educación', 
    'Cuando dice no puedo, quizá necesita otra forma de explicación

Las etiquetas aparecen rápido: “no soy bueno”, “esto no es para mí”. Pero una dificultad específica no define todo su potencial.

En Centro de Tutorías, creamos un espacio seguro para preguntar, reconstruir bases y experimentar avances que cambien su relación con el curso.

Encuentra el apoyo correcto: https://www.centrodetutorias.com
Chatea con nosotros por WhatsApp: https://wa.me/50257152096', 
    'https://www.facebook.com/centrodetutoriasgt/posts/pfbid02wsQmmWKC6VPKs3s89dRY1Lsvhx8S2BwcWtp4s5bcbqAk3JETm9uhXHYXo9JrJxfjl', 
    4, 
    10, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0.0, 
    0.0, 
    0, 
    0.0
) ON CONFLICT (publication_id, platform) DO UPDATE SET
    reach = EXCLUDED.reach,
    views = EXCLUDED.views,
    reactions = EXCLUDED.reactions,
    comments = EXCLUDED.comments,
    shares = EXCLUDED.shares,
    total_clicks = EXCLUDED.total_clicks,
    link_clicks = EXCLUDED.link_clicks,
    engagement_rate = EXCLUDED.engagement_rate,
    ctr = EXCLUDED.ctr,
    avg_watch_time_seconds = EXCLUDED.avg_watch_time_seconds,
    updated_at = timezone('utc'::text, now());

INSERT INTO public.social_media_performance (
    publication_id, platform, published_at, format, message_type, content_intent, 
    post_text, permalink, reach, views, reactions, comments, shares, 
    total_clicks, link_clicks, engagement_rate, ctr, video_duration_seconds, avg_watch_time_seconds
) VALUES (
    '1309754408018330', 
    'meta', 
    '06/20/2026 09:27', 
    'Carrusel', 
    'Clase Modelo', 
    'Conversión', 
    'Una clase modelo puede mostrarte qué apoyo necesita realmente

Elegir apoyo académico también requiere confianza. Una primera sesión permite observar el enfoque y resolver preguntas.

En Centro de Tutorías, conversamos sobre el curso, revisamos necesidades y mostramos cómo sería una tutoría enfocada en su situación.

Agenda una clase modelo: https://www.centrodetutorias.com
Chatea con nosotros por WhatsApp: https://wa.me/50257152096', 
    'https://www.facebook.com/centrodetutoriasgt/posts/pfbid02Ywn482R7CPZUj5ZXLFDQm5y71UNusTvxUSPtAmvfbBKrcAA8QRJCTRNm8mMAKnpEl', 
    23, 
    39, 
    2, 
    0, 
    1, 
    0, 
    0, 
    13.04, 
    0.0, 
    0, 
    0.0
) ON CONFLICT (publication_id, platform) DO UPDATE SET
    reach = EXCLUDED.reach,
    views = EXCLUDED.views,
    reactions = EXCLUDED.reactions,
    comments = EXCLUDED.comments,
    shares = EXCLUDED.shares,
    total_clicks = EXCLUDED.total_clicks,
    link_clicks = EXCLUDED.link_clicks,
    engagement_rate = EXCLUDED.engagement_rate,
    ctr = EXCLUDED.ctr,
    avg_watch_time_seconds = EXCLUDED.avg_watch_time_seconds,
    updated_at = timezone('utc'::text, now());

INSERT INTO public.social_media_performance (
    publication_id, platform, published_at, format, message_type, content_intent, 
    post_text, permalink, reach, views, reactions, comments, shares, 
    total_clicks, link_clicks, engagement_rate, ctr, video_duration_seconds, avg_watch_time_seconds
) VALUES (
    '1309744574685980', 
    'meta', 
    '06/20/2026 09:13', 
    'Carrusel', 
    'Clase Modelo', 
    'Conversión', 
    'Una clase modelo puede mostrarte qué apoyo necesita realmente

Elegir apoyo académico también requiere confianza. Una primera sesión permite observar el enfoque y resolver preguntas.

En Centro de Tutorías, conversamos sobre el curso, revisamos necesidades y mostramos cómo sería una tutoría enfocada en su situación.

Agenda una clase modelo: https://www.centrodetutorias.com
Chatea con nosotros por WhatsApp: https://wa.me/50257152096', 
    'https://www.facebook.com/centrodetutoriasgt/posts/pfbid05m7U3LCyknL5r3GMhaFzjDcCuXgWQ5VHSHaK8VgoCy2eZRXt5zxMBJ5XYUbEBunGl', 
    1, 
    1, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0.0, 
    0.0, 
    0, 
    0.0
) ON CONFLICT (publication_id, platform) DO UPDATE SET
    reach = EXCLUDED.reach,
    views = EXCLUDED.views,
    reactions = EXCLUDED.reactions,
    comments = EXCLUDED.comments,
    shares = EXCLUDED.shares,
    total_clicks = EXCLUDED.total_clicks,
    link_clicks = EXCLUDED.link_clicks,
    engagement_rate = EXCLUDED.engagement_rate,
    ctr = EXCLUDED.ctr,
    avg_watch_time_seconds = EXCLUDED.avg_watch_time_seconds,
    updated_at = timezone('utc'::text, now());

INSERT INTO public.social_media_performance (
    publication_id, platform, published_at, format, message_type, content_intent, 
    post_text, permalink, reach, views, reactions, comments, shares, 
    total_clicks, link_clicks, engagement_rate, ctr, video_duration_seconds, avg_watch_time_seconds
) VALUES (
    '1309039081423196', 
    'meta', 
    '06/19/2026 12:19', 
    'Carrusel', 
    'Confianza', 
    'Educación', 
    'Recuperar la confianza también es parte de aprender matemática

Cuando un estudiante anticipa que fallará, participa menos y practica con inseguridad. Esa experiencia también necesita atención.

En Centro de Tutorías, trabajamos con metas pequeñas, retroalimentación clara y práctica guiada para recuperar autonomía académica.

Acompáñalo paso a paso: https://www.centrodetutorias.com
Chatea con nosotros por WhatsApp: https://wa.me/50257152096', 
    'https://www.facebook.com/centrodetutoriasgt/posts/pfbid08qZXYVSiiD5BhyQ7FY1BtowGpoeegMTDJjrmw25tG1W14UcS6fXehemZSraw4FfNl', 
    19, 
    35, 
    1, 
    0, 
    1, 
    0, 
    0, 
    10.53, 
    0.0, 
    0, 
    0.0
) ON CONFLICT (publication_id, platform) DO UPDATE SET
    reach = EXCLUDED.reach,
    views = EXCLUDED.views,
    reactions = EXCLUDED.reactions,
    comments = EXCLUDED.comments,
    shares = EXCLUDED.shares,
    total_clicks = EXCLUDED.total_clicks,
    link_clicks = EXCLUDED.link_clicks,
    engagement_rate = EXCLUDED.engagement_rate,
    ctr = EXCLUDED.ctr,
    avg_watch_time_seconds = EXCLUDED.avg_watch_time_seconds,
    updated_at = timezone('utc'::text, now());

INSERT INTO public.social_media_performance (
    publication_id, platform, published_at, format, message_type, content_intent, 
    post_text, permalink, reach, views, reactions, comments, shares, 
    total_clicks, link_clicks, engagement_rate, ctr, video_duration_seconds, avg_watch_time_seconds
) VALUES (
    '1309009468092824', 
    'meta', 
    '06/19/2026 11:30', 
    'Carrusel', 
    'Confianza', 
    'Educación', 
    'Recuperar la confianza también es parte de aprender matemática

Cuando un estudiante anticipa que fallará, participa menos y practica con inseguridad. Esa experiencia también necesita atención.

En Centro de Tutorías, trabajamos con metas pequeñas, retroalimentación clara y práctica guiada para recuperar autonomía académica.

Acompáñalo paso a paso: https://www.centrodetutorias.com
WhatsApp: +502 5715 2096', 
    'https://www.facebook.com/centrodetutoriasgt/posts/pfbid02YXeCXEcv2QLmmihH5C1X2ULHa5p3ihVmt8zvUvcVsirpN39fgyr1J3vxNrxgemuwl', 
    4, 
    10, 
    0, 
    0, 
    0, 
    2, 
    1, 
    0.0, 
    50.0, 
    0, 
    0.0
) ON CONFLICT (publication_id, platform) DO UPDATE SET
    reach = EXCLUDED.reach,
    views = EXCLUDED.views,
    reactions = EXCLUDED.reactions,
    comments = EXCLUDED.comments,
    shares = EXCLUDED.shares,
    total_clicks = EXCLUDED.total_clicks,
    link_clicks = EXCLUDED.link_clicks,
    engagement_rate = EXCLUDED.engagement_rate,
    ctr = EXCLUDED.ctr,
    avg_watch_time_seconds = EXCLUDED.avg_watch_time_seconds,
    updated_at = timezone('utc'::text, now());